Tugas_2_PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import update_status.urls as update_status
import halaman_riwayat.urls as halaman_riwayat
import page_profile.urls as page_profile
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update_status/', include(update_status,namespace='update-status')),

    url(r'^page_profile/', include(page_profile,namespace='page-profile')),
    # url(r'^$', RedirectView.as_view(url='page_profile/',permanent=True),name='$'),

    url(r'^halaman_riwayat/', include(update_status,namespace='halaman-riwayat')),

    url(r'^$', RedirectView.as_view(url='update_status/',permanent=True),name='$'),

]

my_profile/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # index dan dashboard
    url(r'^$', index, name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import *
from page_profile.views import edit_profile
#import view profile


from .custom_auth import auth_login, auth_logout

urlpatterns = [
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # index dan dashboard
    url(r'^$', index, name='index'),
    url(r'^dashboard/edit_profile', edit_profile, name='edit_profile'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^add_status/', add_status, name='add_status'),
    url(r'^delete/(?P<id>\d+)/', delete_status, name='delete'),
]

my_profile/models.py
from django.db import models

# Create your models here.

my_profile/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from datetime import *

response = {}
def index(request):
    response['author'] = 'jojo'
    html = 'my_profile/myNew.html'
    return render(request, html, response)

my_profile/templates/my_profile/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p>Made with Love by {{author}}</p>

my_profile/templates/my_profile/partials/header2.html
<!-- templates/lab_7/partials/header.html -->
<nav>
  <div class="container">
    <div class="navbar-header navbar navbar-default">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-static-top" href="{% url 'update-status:index' %}">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse navbar-static-top">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <!-- <li><a href="{% url 'update-status:auth_logout' %}" class="btn btn-default btn-danger">Logout</a> </li> -->
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>