Tugas_2_PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import update_status.urls as update_status
import halaman_riwayat.urls as halaman_riwayat
import page_profile.urls as page_profile
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update_status/', include(update_status,namespace='update-status')),

    url(r'^page_profile/', include(page_profile,namespace='page-profile')),
    # url(r'^$', RedirectView.as_view(url='page_profile/',permanent=True),name='$'),

    url(r'^halaman_riwayat/', include(update_status,namespace='halaman-riwayat')),

    url(r'^$', RedirectView.as_view(url='update_status/',permanent=True),name='$'),

]

my_profile/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # index dan dashboard
    url(r'^$', index, name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import *
from page_profile.views import edit_profile
#import view profile


from .custom_auth import auth_login, auth_logout

urlpatterns = [
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # index dan dashboard
    url(r'^$', index, name='index'),
    url(r'^dashboard/edit_profile', edit_profile, name='edit_profile'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^add_status/', add_status, name='add_status'),
    url(r'^delete/(?P<id>\d+)/', delete_status, name='delete'),
]

update_status/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import pytz

# Create your models here.
class Pengguna(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, )
    nama = models.CharField('Nama', max_length=200)
    created_at = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=7))
    updated_at = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=7))

class Status(models.Model):
    pengguna = models.ForeignKey(Pengguna)
    status = models.CharField(max_length=1000)
    created_date = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=7))

    def as_dict(self):
        return {
            "status": self.status,
            "created_date": self.created_date,
        }
        
class Comment(models.Model):
	pengguna = models.ForeignKey(Status,on_delete=models.CASCADE)
	comment = models.CharField(max_length=1000)
	created_date = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=7))

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        
    }
    status_attrs = {
        'type': 'text',
        'cols' : 149,
        'rows' : 4,
        'class' : 'status-form-input',
        'placeholder' : 'Apa yg anda pikirkan?'
    }

   
    status = forms.CharField(label='',widget=forms.Textarea(attrs=status_attrs), required=True)

update_status/views.py
from __future__ import unicode_literals

import json
from .forms import Status_Form
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
import pytz
from datetime import *
from .models import Pengguna, Status, Comment
from halaman_riwayat import views 
from django.core import serializers

response = {}
def index(request):
    # print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('update-status:dashboard'))
    else:
        response['author'] = get_data_user(request, 'user_login')
        html = 'update_status/login.html'
        return render(request, html, response)


def dashboard(request):
	if 'user_login' not in request.session:
		response['author'] = get_data_user(request, "user_login")
		html = 'update_status/login.html'
		return render(request, html, response)
	else:
		set_data_for_session(request)
		kode_identitas = get_data_user(request, 'kode_identitas')
		try:
			pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
		except Exception as e:
			pengguna = create_new_user(request)
		response['Status_form'] = Status_Form
		kode_identitas = get_data_user(request,'kode_identitas')
		pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
		response['status'] = pengguna.status_set.all().order_by('-id')
		response['daftar_riwayat'] = views.get_daftar_riwayat()
		# print(response['status'])
		# stat = Status.objects.all().order_by('-id')
		stat = pengguna.status_set.all().order_by('-id')
		if (len(stat) > 0):
			message = stat[0]
			newMessage = message.status
			time = message.created_date
		else:
			newMessage = "You have not posted yet" 
			time = date(datetime.now().year,datetime.now().month,datetime.now().day)
		# response['headline'] = response.session['link']
		response['jumlah_status'] = pengguna.status_set.count()
		response['latestMessage'] = newMessage
		html = 'update_status/dashboard.html'
		return render(request, html, response)

def add_status(request):
	kode_identitas = get_data_user(request,'kode_identitas')
	pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		status = Status(status=response['status'], pengguna=pengguna)
		status.save()
	return HttpResponseRedirect(reverse('update-status:dashboard'))

def delete_status(request, id):
	kode_identitas = get_data_user(request,'kode_identitas')
	pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
	status = pengguna.status_set.filter(pk=id)
	status.delete()
	return HttpResponseRedirect(reverse('update-status:dashboard'))


def get_data_user(request, tipe):
    data = None
    if tipe == "user_login" and 'user_login' in request.session:
        data = request.session['user_login']
    elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
        data = request.session['kode_identitas']

    return data

def create_new_user(request):
    nama = get_data_user(request, 'user_login')
    kode_identitas = get_data_user(request, 'kode_identitas')

    pengguna = Pengguna()
    pengguna.kode_identitas = kode_identitas
    pengguna.nama = nama
    pengguna.save()

    return pengguna


def set_data_for_session(request):
    response['author'] = get_data_user(request, 'user_login')
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']

update_status/templates/update_status/dashboard.html
{% extends "update_status/layout/base.html" %}

{% block content %}

<link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">

<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" type="text/css" />
  
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>

<style type="text/css" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></style>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<style type="text/css">
.font1{
    font-family: 'Spectral SC', serif;
}
.part2-info_user .glyphicon-user{
  font-size: 150px;
    color: red
}
.buttonPertama{
  margin-bottom: 20px;
}
.myData{
  
  padding: 10px;
}
.part2 a{
  margin-bottom: 30px;
  margin-left: 30px;
}
.part2_info_user{
  background-color: #C8D8DE;
  padding: 10px;
  border-radius: 10px;
}
.media-left .glyphicon-user{
font-size: 50px;
margin-right: 30px;
}
.kotak{
background-color: #e6e6e6;
border-radius: 10px;
margin-bottom: 20px;
}
.page1{
    top: -120px;
}
.row .btn-danger{
    margin-top: 40px;
}
#menu3{
  position: relative;
  margin-top: -400px;
}

#menu2{
  position: relative;
  margin-top: -300px;
}
</style>
<div class="container page1">
  <div class="col-md-8 font1"><h1>Selamat datang {{ author }}</h1></div>
  
  <div class="col-md-4">
    <a href="{% url 'update-status:auth_logout' %}" class="btn btn-danger btn-lg" onclick="return confirm('Keluar?')">Logout </a>
  </div>
</div>
<div class="container part2">
  <div class="col-md-4 part2_info_user">
    <span class="glyphicon glyphicon-user pull-left" style="font-size:150px;"></span>
    <a href="#" class="btn btn-lg btn-info ">Lihat Forum</a>
    <a href="#" class="btn btn-lg btn-default">Update Status</a>
    <a href="edit_profile.html" class="btn btn-lg btn-default">Edit Profil</a>
  </div>
  <div class="col-md-4">
    <h2 class="font1">Jumlah Status : {{jumlah_status}}</h2>
    <h2 class="font1">Last Comment : {{ latestMessage }}</h2>
  </div>
  <div class="col-md-4"></div>
</div>

<div class="container part3">
<form id="form" method="POST" action="{% url 'update-status:add_status' %}">
                    <h2><strong>Input Status..</strong></h2>
                    {% csrf_token %}
                    {{ Status_form }}
                    <br><input id="submit" type="submit" class="btn btn-md btn-info" value="Submit">
                    <br><br>
                </form>
</div>

<div class="container">
  <h2 class="font1">Let's see what you've got!</h2>
  <p>Click tab below.</p>

  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home" onclick="myFunction_reload()">Status</a></li>
    <li><a data-toggle="tab" href="#menu1" onclick="my_function()">Profile</a></li>
    <li><a data-toggle="tab" href="#menu2" onclick="my_function()">Riwayat</a></li>
    <li><a data-toggle="tab" href="#menu3" onclick="my_function()">Teman</a></li>
    
  </ul>

  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <div id="hide_this">
      <h3>Status</h3>
      {% include 'update_status/tables/status.html' %}  
      </div>
    </div>
    <div id="menu1" class="tab-pane fade">
      <h3>Your Profile</h3>
      {% include 'page_profile/page_profile.html' %}
    </div>
    <div id="menu2" class="tab-pane fade">
      <h3>Riwayat </h3>
      <br>
      {% include 'halaman_riwayat/riwayat.html' %}
    </div>
    <div id="menu3" class="tab-pane fade">
      <h3>Mahasiswa</h3>
      {% include 'cari_mahasiswa/tables/mahasiswa.html' %}
    </div>
  </div>
  </div>
</div>
<script type="text/javascript">

  function my_function(){
    console.log('my_function')
      $("#hide_this").hide();
        $("#menu1").show();
      $("#menu2").show();
      $("#menu3").show();
  }

  function myFunction_reload() {
    $("#hide_this").show();
      $("#menu1").hide();
      $("#menu2").hide();
      $("#menu3").hide();
}

  $(document).ready(function(){
    console.log("JQuery nyala")
    function hide_this(){
      console("masuk hide_this()")
      $("hide_this").html("");
    }
  });
</script>    
{% endblock %}

update_status/templates/update_status/login.html
{% extends "update_status/layout/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'update-status:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}